### ISSUE TITLE
Support for POCKETBOOK_IMPROVED (aka era)

### ISSUE THREAD

**Issue by cy8aer** [kyxap/koreader-calibre-plugin#17]
As I can see the koreader-calibre-plugin 0.5.2 works with the PocketBook Era (which is shown as POCKETBOOK_IMPROVED). So a official support would be nice.

**Comment by Biep** [comment]
It does not sync the rating.  Books I rated on the Era remain without rating in Calibre.
It would also be great if the evaluation text from the book status could be imported into Calibre - or, ideally, **all** the metadata.
Or am I missing something, and is this already possible?

**Comment by kyxap** [comment]
hey @Biep @cy8aer can you check latest release and tell if this still does not work? and if does not could you provide more details with screenshots and expected vs actual results? thanks

**Comment by cy8aer** [comment]
Sorry for the late answer: it works for me.
