### ISSUE TITLE
Support Kobo Clara bw ? 

### ISSUE THREAD

**Issue by kyxap** [kyxap/koreader-calibre-plugin#22]
Hi there,

I don't see this in supported devices so i'm assume there not way the sync plugin will work?
I was expecting to pull highlights from the device via usb.

Currently when I'm trying to do so I'm getting:

```bash
calibre, version 7.10.0
ERROR: No metadata could be synced: Attempted to sync 1.
Metadata sync succeeded for 0.
Metadata sync failed for 1.
(Failures may just be because you have not opened every book in KOReader yet. See below for details.

[
  {
    "result": "could not find uuid in calibre\u2019s library",
    "book_uuid": null,
    "sidecar_path": "E:\\koreader.sdr/metadata.png.lua",
    "updated": "{}"
  }
]
``` 

<img width="425" alt="image" src="https://github.com/harmtemolder/koreader-calibre-plugin/assets/3080529/226b4676-7977-42eb-ad8a-ff2d3238230e">

**Comment by charlesangus** [comment]
Sounds like you don't have any books on the device.

--
416-835-0314

**Comment by kyxap** [comment]
@charlesangus im not just having books on the reader (side loaded) but I've send one via calibre just in case

**Comment by charlesangus** [comment]
Reading the error, the only "book" being found is the png from Koreader, so I think you either don't have the books loaded correctly, or don't have calibre pointing to their location correctly, or something like that that's leading the plugin to not find them.

**Comment by kyxap** [comment]
I've tried to upload the book via wifi and that was successful and also was able to "sync".... 

upd: yeah so sync seems to be working via wifi,,, but actually can't sync any data except that the book is on the device or no...
anyway, too much trouble for simple book upload

**Comment by charlesangus** [comment]
Closing this as it seems to be a Calibre issue.
