### ISSUE TITLE
subproperty "bookmarks" not found in value

### ISSUE THREAD

**Issue by kyxap** [kyxap/koreader-calibre-plugin#23]
Hi there, I've finally managed to configure the sync plugin but there some missing properties in the sidecar json, which plugin can't parse and seems like that why im not getting data populated in calibre. 

Debug outputs:
```bash
DEBUG:   43.5 koreader:action:KoreaderAction:sync_to_calibre:subproperty "bookmarks" not found in value
DEBUG:   43.5 koreader:action:KoreaderAction:sync_to_calibre:subproperty "last_bookmark" not found in value
DEBUG:   43.5 koreader:action:KoreaderAction:sync_to_calibre:subproperty "date_sidecar_modified" not found in value
```

How my raw data looks like:

```json
{
  "annotations": {
    "1": {
      "chapter": "some",
      "datetime": "2024-05-13 06:58:58",
      "drawer": "lighten",
      "note": "test note",
      "page": "/body/DocFragment[28]/body/div[21]/text().17",
      "pageno": 460,
      "pos0": "/body/DocFragment[28]/body/div[21]/text().17",
      "pos1": "/body/DocFragment[28]/body/div[21]/text().120",
      "text": "some"
    },
   
  },
  "cache_file_path": "./cache/cr3cache/some_210_.epub.ebe4fdfa.1.cr3",
  "config_panel_index": 1,
  "copt_b_page_margin": 15,
  "copt_block_rendering_mode": 3,
  "copt_cjk_width_scaling": 100,
  "copt_embedded_css": 1,
  "copt_embedded_fonts": 1,
  "copt_font_base_weight": 0,
  "copt_font_gamma": 15,
  "copt_font_hinting": 2,
  "copt_font_kerning": 3,
  "copt_font_size": 22,
  "copt_h_page_margins": {
    "1": 10,
    "2": 10
  },
  "copt_line_spacing": 100,
  "copt_nightmode_images": 1,
  "copt_render_dpi": 96,
  "copt_rotation_mode": 0,
  "copt_smooth_scaling": 0,
  "copt_status_line": 1,
  "copt_sync_t_b_page_margins": 0,
  "copt_t_page_margin": 15,
  "copt_view_mode": 0,
  "copt_visible_pages": 1,
  "copt_word_expansion": 0,
  "copt_word_spacing": {
    "1": 95,
    "2": 75
  },
  "cre_dom_version": 20240114,
  "css": "./data/epub.css",
  "doc_pages": 676,
  "doc_path": "/mnt/onboard/ebooks/some.epub",
  "doc_props": {
    "authors": "some",
    "description": "some.",
    "identifiers": "uuid:some\\\ncalibre:some\\\nGOOGLE:some",
    "keywords": "nonf_biography",
    "language": "ru",
    "title": "some"
  },
  "floating_punctuation": 0,
  "font_face": "Noto Serif",
  "font_family_fonts": {},
  "handmade_flows_edit_enabled": true,
  "handmade_flows_enabled": false,
  "handmade_toc_edit_enabled": true,
  "handmade_toc_enabled": false,
  "hide_nonlinear_flows": false,
  "highlight_drawer": "lighten",
  "hyph_force_algorithmic": false,
  "hyph_soft_hyphens_only": false,
  "hyph_trust_soft_hyphens": false,
  "hyphenation": true,
  "inverse_reading_order": false,
  "last_xpointer": "/body/DocFragment[28]/body/div[29]/text().88",
  "page_overlap_style": "dim",
  "partial_md5_checksum": "some",
  "partial_rerendering": true,
  "percent_finished": 0.68491124260355,
  "preferred_dictionaries": {},
  "readermenu_tab_index": 1,
  "show_overlap_enable": false,
  "stats": {
    "authors": "some",
    "highlights": 4,
    "language": "ru",
    "notes": 1,
    "pages": 676,
    "performance_in_pages": {},
    "series": "N/A",
    "title": "some"
  },
  "summary": {
    "modified": "2024-05-12",
    "status": "reading"
  },
  "text_lang": "ru",
  "text_lang_embedded_langs": true,
  "toc_ticks_ignored_levels": {}
}
```

Ver:
koreader-kobo-v2024.04-32-geb6e5e3c2_2024-05-10 
Kobo Clara bw

**Comment by kyxap** [comment]
@harmtemolder hey any chance you can get notification if tag you?

**Comment by harmtemolder** [comment]
Hi @kyxap, thanks for picking this up. As you've noticed I'm not actively maintaining this plugin. I see you've forked it, did some cleanup, and fixed a couple of things. Shall I make you a contributor, so you can merge it yourself? And are you willing to look at other open issues as well?

**Comment by kyxap** [comment]
@harmtemolder sure!

btw how does new release became available in calibre plugin search? I'm not sure what is required to make it happen

**Comment by harmtemolder** [comment]
I don't actually remember. I believe it is linked to https://www.mobileread.com/forums/showthread.php?p=4060545 somehow. Although I do remember an issue where I was working in a separate branch on https://github.com/harmtemolder/koreader-calibre-plugin and users reporting that they were getting that branch when installing through calibre. So it might be that calibre just takes the latest commit in any branch.

**Comment by kyxap** [comment]
@harmtemolder ok so seems like release is pull from the post attachments, based on:

<img width="557" alt="image" src="https://github.com/user-attachments/assets/a302d1c8-0916-4853-8e42-c896e889773c">

https://www.mobileread.com/forums/showthread.php?t=118764

idk but maybe you can ask forum moderators to give me access to change that thread/post (not sure if its possible but better ask I guess)

as alternative we can create new thread update the index and will be updating the latest release there

**Comment by kyxap** [comment]
@harmtemolder ok after looking into how other people do this, they just create new thread and updating the index.
I've created thread here: https://www.mobileread.com/forums/showthread.php?p=4441614#post4441614
So could you ask admins for index update? And maybe update your [original](https://www.mobileread.com/forums/showthread.php?p=4060545) post with the link to new thread?

**Comment by harmtemolder** [comment]
I see that `pdurrant` updated the old thread. Does that mean calibre now picks up on your new thread?

**Comment by kyxap** [comment]
Yeah
