### ISSUE TITLE
Can't find plugin >0.5.2 inside Calibre

### ISSUE THREAD

**Issue by Kageetai** [kyxap/koreader-calibre-plugin#29]
As the title says, can't install any newer version than 0.5.2 inside Calibre. Is there some release missing? Or do I need some step to update. I guess I will install from a file, but would be nice to be able to update directly.

**Comment by Kageetai** [comment]
![Screenshot 2024-07-28 at 15 07 13](https://github.com/user-attachments/assets/8eb185a0-567c-4dda-9ef7-ef386802c874)

**Comment by kyxap** [comment]
Yeah it’s expected at this moment. I’m working with  @harmtemolder to resolve this issue. Nothing can be done from my side and not sure how long it will take to make it happen. 

So you need to wait or update it manually. Zip is attached in release. Readme has instructions

**Comment by kyxap** [comment]
I've created #30 with more details

**Comment by Kageetai** [comment]
Okay, that's more or less what I thought, thanks for the explanation. I installed it manually
