### ISSUE TITLE
Cannot choose sync option

### ISSUE THREAD

**Issue by glrbl** [kyxap/koreader-calibre-plugin#33]
Hello,

All the sync option are disabled and I cannot change them:

<img width="366" alt="image" src="https://github.com/user-attachments/assets/0a9719d8-898c-4727-8ae8-806206e26530">

Calibre 7.13. It is my first time using this plug-in so I am not sure If I am missing something.

Best,

**Comment by kyxap** [comment]
This is expected, you need to follow setup steps and create/assign columns, see readme: https://github.com/harmtemolder/koreader-calibre-plugin?tab=readme-ov-file#setup
