### ISSUE TITLE
Koreader star ratings cut in half in calibre

### ISSUE THREAD

**Issue by sztanj** [kyxap/koreader-calibre-plugin#36]
Hello,
On the latest release of the plugin I noticed that on-device rating is now cut in half in calibre after successful sync of koreader metadata to calibre.

5-star in koreader => 2-star in calibre
3-star in koreader => 1-star in calibre

I use the default built-in "rating" column in calibre. It seems this column is an integer from 0 to 10 as mentioned in an [old mobilereads post](https://www.mobileread.com/forums/showpost.php?p=3568446&postcount=3), but I was not able to find any official documentation of that.

**Versions**
KOreader Sync 0.6.5
Calibre 6.28.1 

Below please see the raw sidecar data (also synced via koreader sync) showing a rating of 3, but only 1 star in the calibre "rating" column.
![240808 koreader sync ratings mismatch](https://github.com/user-attachments/assets/45fd5de6-4bdf-4391-aa26-8951a545128d)

Thank you.

**Comment by kyxap** [comment]
What Koreader version you are using ?

**Comment by kyxap** [comment]
ok I found the issue, should be fixed in new release. Let me know if it still does not work

**Comment by sztanj** [comment]
Thank you very much!
I'm running Koreader v2024.07.
I tested with the new release v0.6.6 of Koreader sync (with the "sync only if changes are newer" checkbox turned off) and the issue was fixed, with all the ratings correct now.
