### ISSUE TITLE
Add column for sidecar modified date

### ISSUE THREAD

**Issue by harmtemolder** [kyxap/koreader-calibre-plugin#4]
(Copied from [#14 on sourcehut](https://todo.sr.ht/~harmtemolder/koreader-calibre-plugin/14).)

>USB devices allow for direct access of files over the file system, so we could use that to get the actual last modified date (credits to Hyphen-ated on MobileRead: https://www.mobileread.com/forums/showpost.php?p=4273289&postcount=77).
>
>Don't forget to add an asterisk to the README saying that this will not work for all devices. Come to think of it: test what happens on an unsupported device.

**Comment by charlesangus** [comment]
Fixed in v0.5.1
