### ISSUE TITLE
[FEATURE] Sync the KOReader history with Calibre

### ISSUE THREAD

**Issue by WillScarlettOhara** [kyxap/koreader-calibre-plugin#46]
### Feature Summary

Sync the KOReader history with Calibre

### Motivation

I want to be able to change a broke e-reader without loosing anything.

### Use Cases

When I synchronize my reading progress on KOReader from Calibre, I don't get the information that this book was opened second to last, for example.

**Comment by kyxap** [comment]
Define **KOReader history** please

> I want to be able to change a broke e-reader without loosing anything.

how sync plugin can help you with it?

> When I synchronize my reading progress on KOReader from Calibre, I don't get the information that this book was opened second to last, for example.

what actually you want to see in calibre after sync? column when book was last time opened? if so is this information available in koreader sidecar?

**Comment by WillScarlettOhara** [comment]
Last time opened would be nice but I don't know if it's within the sidecar and I don't know whether it's from this metadata that KOReader's History screen is sorted.

**Comment by kyxap** [comment]
could you check if "history" in the sidecar on your device?

**Comment by WillScarlettOhara** [comment]
Unfortunately, I can't see any reference to it.

**Comment by kyxap** [comment]
then this is not something that we can do with current koreader implementation
