### ISSUE TITLE
[FEATURE] Sync tags in both directions to take advantage of KOReader's new collections feature

### ISSUE THREAD

**Issue by WillScarlettOhara** [kyxap/koreader-calibre-plugin#48]
### Feature Summary

Add the ability to sync tags in both directions to take advantage of KOReader's new collections feature

### Motivation

[Like others](https://github.com/koreader/koreader/issues/8472#issuecomment-2308988991), I don't really like the way I browse and display my books on KOReader. A small compensation would be to be able to sort my books by category.

### Use Cases

I'd like to be able to create collections from Calibre and place my books in them with a single click.

### Alternatives

A collection by Calibre tag or a new column on purpose. Both to let the choice.

**Comment by kyxap** [comment]
Sorry I'm not following, what are those `tags` where do I find them? Is there any documentation?

**Comment by kyxap** [comment]
> I'd like to be able to create collections from Calibre and place my books in them with a single click.

it does not sound like something related to sync plugin or I'm missing something?

**Comment by WillScarlettOhara** [comment]
> Sorry I'm not following, what are those `tags` where do I find them? Is there any documentation?

Tags are a default column in Calibre.
![image](https://github.com/user-attachments/assets/d368122e-07d9-48ff-ae70-b3ba9b800f70)
You can put whatever you like. Personally, I indicate the genre of my books. [https://manual.calibre-ebook.com/sub_groups.html](https://manual.calibre-ebook.com/sub_groups.html)

It would be great to be able to create collections in KOReader and place books in them from this Calibre column.

**Comment by kyxap** [comment]
> create collections in KOReader

I've not used this feature and I can't find it in the menu, where it's located? does koreader support collection creation based on some sidecar data?

**Comment by WillScarlettOhara** [comment]
It's fairly new, so I don't know about the sidecar.

Collections can be found in the top right-hand menu. It's below History and Favorites.
Then you can create collections one by one from there. Good luck when you have twenty tags or so like me.

Then to add a book to a collection:
Long press a book > Add to collection

With my 1,300 books, I'd never take the time to do this manually, even though my books are already well-gendered/well-collectionned in Calibre.

**Comment by kyxap** [comment]
Oh ok... yeah I've added book to the collection but nothing was added to the metadata/sidecar which means it's saves somewhere else e.g. in db. Out of purpose of this plugin
