### ISSUE TITLE
[FEATURE] Manage KOReader collections from Calibre

### ISSUE THREAD

**Issue by zeeyado** [kyxap/koreader-calibre-plugin#54]
### Feature Summary

Ability to create/manage/sync KOReader's built-in Collections feature in Calibre

### Motivation

Organizing books into collections can be a beneficial way to sort your library, as you could have different collections for different projects or explorations you are doing, and a given book could belong to more than one collections.

Collections are not too dissimilar from tags, in principle, but many like to keep tags for basic genres/topics and fetch them from a unified source like Goodreads.

### Use Cases

KOReader has recently added a [collections feature](https://github.com/koreader/koreader/pull/11693), but it is only manageable on-device, which is cumbersome, especially with large libraries.

For instance, you could have a collection for "Winter reading", one for "Read ASAP" and one for "Neuroscience", and a book could belong to all three of those collections. It is simply a practical way to organize, browse, and keep track of your reading, by mood, project, topic, etc.

Having a KOReader collection manager in Calibre would be very practical, as you would be able to curate your collections much better.

Preferably it would sync both ways, so that any collections created on the device would sync back to Calibre, along with the books added to collections on-device. 

### Alternatives

Manage collections on-device only, or get a Kobo device and use Nickel as the Library interface and launch books into KOReader from it, and use the Kobo Calibre plugin to manage collections.

**Comment by kyxap** [comment]
Plugin does not modify koreader db in any way see #48
