### ISSUE TITLE
[Bug]: Unable get highlight from KOReader

### ISSUE THREAD

**Issue by tiankonganddahai** [kyxap/koreader-calibre-plugin#56]
### KOreader Sync plugin version

v0.6.7

### KOreader version

v2023.10

### Operating System

Windows

### Connection type

Wireless (over wifi)

### Describe the bug

First, connect to Calibre from KOReader with wireless
Then click "Sync from koreader" in the plugin menu at calibre.
It shows success, but no highlight in column "bookmarks_and_highlights".

As instructions in readme page, before sync, i already create a column named "bookmarks_and_highlights".
![2024-10-21_221759](https://github.com/user-attachments/assets/88ffa624-d2ec-4be4-b3c2-bebeeaad7fd9)

### How to reproduce

as describe above.

### Expected behavior

After sync, the highlights column show the correct content

### Screenshots

![image](https://github.com/user-attachments/assets/9e105f9f-7de2-4619-abdc-7e5e53a6a17b)

**Comment by kyxap** [comment]
Please read the setup instructions:

https://github.com/harmtemolder/koreader-calibre-plugin?tab=readme-ov-file#setup

Also you need to update your koreader to 2024 version (again see readme)
